[tool.poetry]
name = "mantis"
version = "0.0.1"
description = "Python server which solves problems from provided input and additional data obtained from chains/indexers and outputs single route solution."
authors = []
packages = [
    { include = "simulation" },
    { include = "blackbox" },
    { include = "cvm_runtime", from = "blackbox" },
    { include = "main.py", from = "blackbox" },
]

[tool.poetry.dependencies]
python = "^3.11"
ecdsa = "*"
bech32 = "*"
requests = "*"
protobuf = ">=4.21.6,<5.0dev"
grpcio = "==1.53.2"
jsonschema = ">=3.2.0,<5"
python-dateutil = "*"
pycryptodome = "^3.18.0"
googleapis-common-protos = "*"
numpy = "^1.26.2"
cvxpy = "^1.4.1"
pydantic = "^2.5.3"
strictly-typed-pandas = "^0.1.24"
fastapi = { extras = ["all"], version = "^0.108.0" }
uvicorn = "^0.25.0"
fastapi-cache2 = "^0.2.1"
blackbox = "^0.7.1"
pandas = "^2.1.4"

[tool.poetry.dev-dependencies]
pytest = "^7.4.3"
black = "^23.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
blackbox = 'blackbox.main:start'
