[package]
edition = "2021"
name = "cvm-runtime-exchage"
version = "0.1.0"

[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3"] }
osmosis-std = { workspace = true, default-features = false }

astroport = { workspace = true, default-features = false }


[features]
default = ["std"]
cosmwasm = []
json-schema = [
]
cosmos = []
std = [
]


