[package]
name = "mantis-node"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mantis"

[dependencies]
cw-mantis-order = { path = "../../contracts/cosmwasm/order" }
clap = { workspace = true, features = ["derive"] }
cosmrs = { workspace = true}
bip32 = { workspace = true}


tokio = { workspace = true, features = ["full"] }
cosmos-sdk-proto = { workspace = true, features = ["grpc-transport"] }
tonic = { workspace = true }
rand = { workspace = true, default-features = false }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
rand_distr = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
itertools = { workspace = true }
derive_more = { workspace = true }
serde-json-wasm = { workspace = true }
tuples = { workspace = true }
cosmwasm-std = {workspace = true}