[package]
name = "mantis-node"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mantis"

[dependencies]
bip32 = { workspace = true }
clap = { workspace = true, features = ["derive"] }
cosmos-sdk-proto = { workspace = true, features = ["grpc-transport"] }
cosmrs = { workspace = true }
cosmwasm-std = { workspace = true }
cw-mantis-order = { path = "../../contracts/cosmwasm/order", features = [
    "json-schema",
    "std",
] }
derive_more = { workspace = true }
itertools = { workspace = true }
num-traits = { workspace = true }
prost-types = { workspace = true }
rand = { workspace = true, default-features = false }
rand_distr = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
serde-json-wasm = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
tuples = { workspace = true }
cvm-runtime = { workspace = true, features = ["std"] }