[package]
edition = "2021"
name = "cvm-route"
version = "0.1.0"

[dependencies]
cosmwasm-std = { workspace = true, features = ["ibc3"] }

cvm = { workspace = true }

[features]
default = ["std"]
cosmwasm = []
json-schema = [
]
cosmos = []
std = [
]
